In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('credit_card_data.csv')

In [3]:
df.head()

pop_cd  year  month  avg_score  avg_rat city  sex ages  population  \
0   L011  2016      1        812        2   서울  NaN  10대       55000   
1   L011  2016      2        773        4   서울  NaN  10대      380000   
2   L011  2016      3        771        4   서울  NaN  10대      387000   
3   L011  2016      4        770        4   서울  NaN  10대      412000   
4   L011  2016      5        771        4   서울  NaN  10대      414000   

   num_opencard  ...  monthly_installments_loan  monthly_insurance_loan  \
0          1.44  ...                          0                       0   
1          1.71  ...                     510000                  220000   
2          1.75  ...                     490000                  210000   
3          1.76  ...                     510000                  240000   
4          1.75  ...                     490000                  340000   

   monthly_sbk_loan  loan_commitment  inst_rep_loanb  ls_rep_loanb  \
0                 0          1120000         8210000      78020000   
1           1020000           680000         4660000      23300000   
2           1140000           640000         4370000      22930000   
3           1340000           510000         4770000      22160000   
4           1490000           640000         4740000      21960000   

   credit_loan  mortgage_loan  credit_card_payment  \
0     92170000       87260000                    0   
1      8260000       42410000                 4000   
2      8300000       41710000                 3000   
3      9460000       41040000                 4000   
4      9660000       40850000                 3000   

   credit_card_installments_payment  
0                                 0  
1                              1000  
2                              1000  
3                              1000  
4                              1000  

[5 rows x 26 columns]

In [18]:
df.columns

Index(['year', 'month', 'avg_score', 'avg_rat', 'population', 'num_opencard',
       'num_usecard', 'monthly_card_spend', 'monthly_lc', 'monthly_loan',
       'monthly_bk_loan', 'monthly_cd_loan', 'monthly_installments_loan',
       'monthly_insurance_loan', 'monthly_sbk_loan', 'loan_commitment',
       'inst_rep_loanb', 'ls_rep_loanb', 'credit_loan', 'mortgage_loan',
       'credit_card_payment', 'credit_card_installments_payment'],
      dtype='object')

In [4]:
df = df.drop(['sex','city','ages','pop_cd',],axis=1)

In [67]:
X = df[['population', 'num_opencard',
       'num_usecard', 'monthly_card_spend', 'monthly_lc', 'monthly_loan',
       'monthly_bk_loan', 'monthly_cd_loan', 'monthly_installments_loan',
       'monthly_insurance_loan', 'monthly_sbk_loan', 'loan_commitment',
       'inst_rep_loanb', 'ls_rep_loanb', 'credit_loan', 'mortgage_loan',
       'credit_card_payment', 'credit_card_installments_payment']]
y = df.avg_rat

In [68]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters=3,init='random',max_iter=300,random_state=0)
y_km = km.fit_predict(X)

In [69]:
y_km=y_km+2

In [70]:
from sklearn.metrics import classification_report,confusion_matrix

In [71]:
print(confusion_matrix(df.avg_rat,km.labels_+2))

[[  16    3    1]
 [ 211  915 1762]
 [ 848   43   89]]


In [72]:
print(classification_report(df.avg_rat,km.labels_+2))

              precision    recall  f1-score   support

           2       0.01      0.80      0.03        20
           3       0.95      0.32      0.48      2888
           4       0.05      0.09      0.06       980

   micro avg       0.26      0.26      0.26      3888
   macro avg       0.34      0.40      0.19      3888
weighted avg       0.72      0.26      0.37      3888



In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
from sklearn.model_selection import train_test_split

In [56]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [57]:
Dtree = DecisionTreeClassifier()
Dtree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [58]:
predictions_Decisiontree_model = Dtree.predict(x_test)

In [59]:
print('Decision Tree')
print(confusion_matrix(y_test,predictions_Decisiontree_model))
print(classification_report(y_test,predictions_Decisiontree_model))

Decision Tree
[[  4   0   1]
 [  1 879   7]
 [  0   7 268]]
              precision    recall  f1-score   support

           2       0.80      0.80      0.80         5
           3       0.99      0.99      0.99       887
           4       0.97      0.97      0.97       275

   micro avg       0.99      0.99      0.99      1167
   macro avg       0.92      0.92      0.92      1167
weighted avg       0.99      0.99      0.99      1167



In [60]:
from sklearn.neighbors import KNeighborsClassifier

In [61]:
knn=KNeighborsClassifier(n_neighbors=3)

In [62]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [64]:
predictions = knn.predict(x_test)

In [65]:
confusion_matrix(y_test,predictions)

array([[  4,   1,   0],
       [  0, 887,   0],
       [  0,  17, 258]], dtype=int64)

In [66]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           2       1.00      0.80      0.89         5
           3       0.98      1.00      0.99       887
           4       1.00      0.94      0.97       275

   micro avg       0.98      0.98      0.98      1167
   macro avg       0.99      0.91      0.95      1167
weighted avg       0.98      0.98      0.98      1167

